version: "1.0"
project: "vtopcc"

services:
  vtopcc-backend:
    type: web
    source:
      directory: backend
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    deploy:
      port: 5000
      env:
        NODE_ENV: production
        PORT: 5000
        JWT_SECRET: generated_devpanel_secret
        ADMIN_ROLL_NUMBERS: 25BCE5232

  vtopcc:
    type: static
    source:
      directory: frontend
    buildCommand: "npm install && npm run build"
    build:
      output_dir: dist
