services:
  - type: web
    name: vtopcc-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: vtopcc
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend
    routes:
      - type: rewrite
        source: /api/*
        destination: https://vtopcc-backend.onrender.com/api/*